### ISSUE TITLE
Receiving Messages (besides whispers) no longer working

### ISSUE THREAD

**Issue by Manu311** [theli-ua/honpurple#13]
Messages you receive don't show up.
Pidgin just displays an empty message (it does pop up) and I haven't seen any relevant console output (even with -d).
It does display messages someone whispered to you (or his buddies) and chat room messages are displayed as well - only direct messages are broken.
Also every method of writing to others (by whisper or direct message) does still work.

I assume this is easily reproducible in case someone wants to fix it.

**Comment by K1773R** [comment]
I can confirm this. When you receive a message its parsed as an empty string.

**Comment by theli-ua** [comment]
totally forgot about this, does anyone still care?

**Comment by theli-ua** [comment]
Anyhow, I fixed that in master for anyone who still does.

**Comment by K1773R** [comment]
@theli-ua i still use it, so thanks!
